// Generates src/data.generated.ts from the canonical name data in name/data.
//
// Run via `npm run generate`.

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const dataDir = join(here, "..", "..", "..", "name", "data");
const outFile = join(here, "..", "src", "data.generated.ts");

const CULTURE_BY_KEY = {
  afghan: "Afghan",
  "african-central": "African (Central)",
  "african-southern": "African (Southern)",
  "african-west": "African (West)",
  "american-ibero": "Iberoamerican",
  anglophone: "Anglophone",
  "asian-south": "Asian (South)",
  "asian-southeast": "Asian (Southeast)",
  chinese: "Chinese",
  ethiopian: "Ethiopian",
  "european-central": "European (Central)",
  "european-southern": "European (Southern)",
  fijian: "Fijian",
  french: "French",
  georgian: "Georgian",
  germanic: "Germanic",
  greek: "Greek",
  gulf: "Arabic (Gulf)",
  iranian: "Iranian",
  irish: "Irish",
  japanese: "Japanese",
  korean: "Korean",
  levantine: "Arabic (Levantine)",
  maghrebi: "Arabic (Maghrebi)",
  nordic: "Nordic",
  russian: "Russian",
  "slavic-south": "Slavic (South)",
  turkic: "Turkic",
};

const FIELDS = [
  { suffix: "_given_female.txt", field: "givenFemale" },
  { suffix: "_given_male.txt", field: "givenMale" },
  { suffix: "_surnames.txt", field: "surnames" },
];

const lines = (raw) =>
  raw
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line !== "");

const byCulture = new Map();

for (const file of readdirSync(dataDir)) {
  const match = FIELDS.find(({ suffix }) => file.endsWith(suffix));
  if (!match) continue;

  const key = file.slice(0, -match.suffix.length);
  const culture = CULTURE_BY_KEY[key];
  if (!culture) {
    throw new Error(`No culture mapped for data file key: ${key}`);
  }

  const data = byCulture.get(culture) ?? { givenMale: [], givenFemale: [], surnames: [] };
  data[match.field] = lines(readFileSync(join(dataDir, file), "utf8"));
  byCulture.set(culture, data);
}

// Sort for deterministic output.

const cultures = [...byCulture.keys()].sort();

const literal = (values) => `[${values.map((value) => JSON.stringify(value)).join(", ")}]`;

const entries = cultures
  .map((culture) => {
    const { givenMale, givenFemale, surnames } = byCulture.get(culture);
    return [
      `  ${JSON.stringify(culture)}: {`,
      `    givenMale: ${literal(givenMale)},`,
      `    givenFemale: ${literal(givenFemale)},`,
      `    surnames: ${literal(surnames)},`,
      `  },`,
    ].join("\n");
  })
  .join("\n");

const output = `// Code generated by scripts/generate-data.mjs from name/data; DO NOT EDIT.

import type { IRLCulture } from "./culture.js";
import type { CultureData } from "./data.js";

export const IRL_DATA: Record<IRLCulture, CultureData> = {
${entries}
};
`;

writeFileSync(outFile, output);
